### ISSUE TITLE
Adjust definition for '.ajax_loader' in 'style.scss'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1528]
We will have the following implementation:

```css
...
.ajax_loader {
  background: url('../img/loading.gif') no-repeat center center transparent;
  background-size:90px 90px;
  width:100%; height:100%;
}
```
