### ISSUE TITLE
Validate sass syntax within Travis implementation

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2093]
We need to ensure sass validation within our Travis implementation.  This validation should work in tandem with current python validation.

**Comment by jeff1evesque** [comment]
We need to make a minor comment change.

**Comment by jeff1evesque** [comment]
We need to remove the following from our `.scss-lint.yml`:

```yml
...
  BorderZero:
    enabled: false
...
```
