### ISSUE TITLE
Send '.coverage' docker output to coveralls from travis

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2697]
We will add code coverage (i.e. [coveralls](https://coveralls.io/)) to the travis ci workflow.

**Comment by jeff1evesque** [comment]
6f3441b: the `repo_token` has been regenerated, and not committed within any file in this repository.

**Comment by jeff1evesque** [comment]
This issue is still not resolved.

**Comment by jeff1evesque** [comment]
One approach we can investigate, is to determine if we can write the results of our coverall (executed from [`app.py`](https://github.com/jeff1evesque/machine-learning/blob/3096ce3b14b51da0cf04b11240bdd059b7515d95/app.py#L21) into a file, then let `.travis.yml` read this file, within the following adjusted directive:

```yaml
...
after_success:
  - coveralls
```

This temporary file will only get executed when `pytest.main(['test/live_server'])` is run from `app.py`.  This is specified by corresponding dockerfiles, which get `run` via the project `.travis.yml`.  So, in a typical `git push` workflow, a temporary file will be created.  So, if possible, the onerous will be on reading the temporary file into the `after_success` stanza from the `.travis.yml`.

**Comment by jeff1evesque** [comment]
700bffa, 7f9348f: we add `__init__.py` to several subdirectories within `test/live_server/programmatic_interface`, per https://bitbucket.org/pytest-dev/pytest/issues/529/unique-basename-and-__init__py-docs#comment-10790185.

**Comment by jeff1evesque** [comment]
We have successfully generated a `pytest-cov` [report](https://travis-ci.org/jeff1evesque/machine-learning/builds/192158646#L4076-L4165) from within our docker unit testing environment.  However, general practice is to send this report to [coveralls](https://coveralls.io/github/jeff1evesque/machine-learning) via the following `.travis.yml`:

```yaml
sudo: required
language: python

## build docker, install puppet (i.e. puppet parser validate)
before_install:
  - sudo apt-get update

## install packages for linting
install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - pip install coveralls==1.1

## run coverage
script:
  - coverage run --source=yourpackagename setup.py test

## tell coveralls about coverage
after_success:
  - coveralls
```

However, we ran our `coverage` within a series of docker containers, connected by a common network, spun up by our `.travis.yml`.  These results are returned as stdout traceback, and accessible within our `.travis.yml`.  But, we need to figure our how to `grep` these results into the mechanisms of the above coveralls, and ensure the computed coverage report is sent to our corresponding [coverall page](https://coveralls.io/github/jeff1evesque/machine-learning).
