### ISSUE TITLE
Reduce puppet syntax by iterating 'packages.yaml'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2815]
We should reduce our `puppet/environment/*/package/manifest/*.pp`, by consolidating all the corresponding manifest, into one.  This can be done by iterating the corresponding `hiera/packages.yaml`, instead of defining a puppet manifest for each entry in the `packages.yaml` file.

**Comment by jeff1evesque** [comment]
We need to make sure that there aren't special cases, where some packages within `packages.yaml`, is installed at a location different from `puppet/environment/*/package/manifest/*.pp`.  If the latter is the case, we'll need to make corresponding adjustments within the `packages.yaml` hierarchy.

**Comment by jeff1evesque** [comment]
We can organize our `packages.yaml` structure as follows, where the `general` key would be passed to the puppet iterator logic, while the `special` key could be used within it's own independent scope:

```yaml
##
## This file contains versions of installed packages.
##
development:
    keyserver:
        apt: hkp://keyserver.ubuntu.com:80
        mongodb_key: 0C49F3730359A14518585931BC711F9BA15703C6
        mongodb_source_list: 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse'

    apt:
        general:
            aa: 'bb'
            aa: 'bb'
            aa: 'bb'
        special:
            xx: 'yy'
            xx: 'yy'
            xx: 'yy'

    github:
        general:
            aa: 'bb'
            aa: 'bb'
            aa: 'bb'
        special:
            xx: 'yy'
            xx: 'yy'
            xx: 'yy'

    npm:
        general:
            aa: 'bb'
            aa: 'bb'
            aa: 'bb'
        special:
            xx: 'yy'
            xx: 'yy'
            xx: 'yy'

    pip:
        general:
            aa: 'bb'
            aa: 'bb'
            aa: 'bb'
        special:
            xx: 'yy'
            xx: 'yy'
            xx: 'yy'
```
