### ISSUE TITLE
Restructure 'model_type' in 'application.yaml'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3062]
We need to restructure our `model_type` from `application.yaml`:

```yaml
    model_type:
        - svm
        - svr
        - bagc
        - bagr
```

To the following:

```yaml
    model_type:
        classifiers:
            - svm
            - bagc
        regressors:
            - svr
            - bagr
```

This will means we'll need to refactor various aspects of our application, including [`bagger.py`](https://github.com/jeff1evesque/machine-learning/blob/9f2ccba0f7adb69718a0fcf4e9b65175cacdbf44/brain/session/model/bagger.py#L38-L39):

```python
    classifiers = [list_model_type[3]]
    regressors = [list_model_type[4]]
```

**Note:** there are two instances of the above snippet in `bagger.py`.

**Note:** this issue was motivated by https://github.com/jeff1evesque/machine-learning/pull/3061#issuecomment-336729298.
