### ISSUE TITLE
Ensure 'jquery validation' messages position

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#595]
We will ensure that any _jquery validation_ error messages float to the right of the two _Add more_, and _Remove_ buttons.  This can be achieved by ensuring the following in `style.scss`:

``` css
.svm_dep_variable, .svm_indep_variable, .svm_dataset_file, .svm_dataset_xml {
  float:left; clear:both;
}

.svm_dataset_xml_add, .svm_dataset_file_add, .svm_dep_variable_add, .svm_indep_variable_add, .svm_dataset_xml_remove, .svm_dataset_file_remove, .svm_dep_variable_remove, .svm_indep_variable_remove {
  float:left; clear:none;
}

label.error {
  float:right;
}
```
