### ISSUE TITLE
CSS: select classname except first 'style.scss'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#596]
We will change the following in `style.scss`:

``` css
...
input[name='svm_dataset[]']:not(:first-of-type), input[name='svm_dep_variable[]']:not(:first-of-type), input[name='svm_indep_variable[]']:not(:first-of-type) {
  display:block;
}
...
```

to the following:

``` css
...
input[name='svm_dataset[]']:not(:first-of-type), .svm_dep_variable ~ .svm_dep_variable, .svm_indep_variable ~ .svm_indep_variable {
  display:block;
}
...
```
