### ISSUE TITLE
Adjust 'display' for input elements in 'style.scss'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#854]
After we have [adjusted](https://github.com/jeff1evesque/machine-learning/issues/853) the `fieldset_session_training` fieldset, we will add the following in `style.scss`:

```css
input[name='svm_title'] {
  display:block
}

input[name='svm_model_type'] {
  display:inline-block
}
```
